apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: drissahd/devops_backend
          ports:
            - containerPort: 8000
          env:
            - name: MONGO_URI
              value: mongodb://mongo:27017/netflix-app